name: Debug MacOS
on: [ workflow_dispatch ]   # Workflow is triggered manually

jobs:
  debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Pre-install some Homebrew packages:
      - name: Install custom packages
        run: |
          brew install -y bash cmake figlet gnu-getopt gettext git joe make pwgen wget
          brew install -y libidn2 libmaxminddb
          brew install -y bison
          brew install -y boost
          brew install -y exiftool ghostscript GraphicsMagick mupdf-tools nss

      # Clone some repositories:
      - name: Clone repositories
        run: |
          git clone https://dreibh@github.com/dreibh/bibtexconv
          git clone https://dreibh@github.com/dreibh/fractgen
          git clone https://dreibh@github.com/dreibh/hipercontracer
          git clone https://dreibh@github.com/dreibh/netperfmeter
          git clone https://dreibh@github.com/dreibh/rsplib
          git clone https://dreibh@github.com/dreibh/rserpooldemo
          git clone https://dreibh@github.com/dreibh/sctplib
          git clone https://dreibh@github.com/dreibh/socketapi
          git clone https://dreibh@github.com/dreibh/subnetcalc
          git clone https://dreibh@github.com/dreibh/system-tools
          git clone https://dreibh@github.com/dreibh/tsctp

      # This action sets up tmate and gives you an SSH connection string:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true   # Only allow you to connect
